version: "4.0"

services:
  app:
    image: soumendra08/backend:1.0.0
    ports:
      - 1200:1200
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devproject?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devproject
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
